### ISSUE TITLE
Code Documentation (functions, classes, etc)

### ISSUE THREAD

**Issue by felipebulcao** [RitsuProject/ritsu-v3#47]
As in V2, it is good to try to document each function or class so that the understanding of the code is better, I have already done this in some classes but I think they can still be improved.

One solution to this would be JSDocs.

**Comment by Lioness100** [comment]
https://www.npmjs.com/package/typedoc is another good option :)

**Comment by felipebulcao** [comment]
Basically made this on 0d375ea, I'll dont try to add comments on everything and instead I think its better to just follow the argument that "less comments = better code" and because of this, I refactored a bunch of things.
